"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type BlockType="Text"|"Video"|"Image"|"Document"|"Checklist"|"Question"|"Manager Sign-Off";
type Block={id:number;type:BlockType;title:string;content:string};
const defaults:Block[]=[
{id:1,type:"Text",title:"Lesson Introduction",content:"Explain what the employee will learn and why it matters."},
{id:2,type:"Video",title:"Service Video Example",content:"Watch this example of excellent service at Roberto's."},
{id:3,type:"Checklist",title:"Key Steps Checklist",content:"Greet every table promptly\nIntroduce yourself and Roberto's\nPresent menus and answer initial questions\nTake drink orders immediately\nReturn with drinks and take food orders\nCheck back within 2 minutes after food delivery\nAnticipate needs and keep the table comfortable"},
{id:4,type:"Question",title:"Knowledge Check",content:"Test what you've learned in this lesson."}
];
const meta:Record<BlockType,{icon:string;hint:string}>={Text:{icon:"▤",hint:"Text"},Video:{icon:"▶",hint:"Video"},Image:{icon:"▧",hint:"Image"},Document:{icon:"□",hint:"Document"},Checklist:{icon:"☑",hint:"Checklist"},Question:{icon:"?",hint:"Question"},"Manager Sign-Off":{icon:"♙",hint:"Manager Sign-Off"}};
export default function LessonEditor(){
 const [title,setTitle]=useState("Steps of Service"),[description,setDescription]=useState("Learn the step-by-step process for providing excellent service at Roberto’s, from greeting the guest to closing the check."),[minutes,setMinutes]=useState("10"),[required,setRequired]=useState(true),[blocks,setBlocks]=useState<Block[]>(defaults),[saved,setSaved]=useState("");
 useEffect(()=>{const raw=localStorage.getItem("robertos-lesson-draft");if(raw)try{const d=JSON.parse(raw);setTitle(d.title||title);setDescription(d.description||description);setMinutes(d.minutes||minutes);setRequired(d.required??true);setBlocks(d.blocks||defaults)}catch{}},[]);
 function save(){localStorage.setItem("robertos-lesson-draft",JSON.stringify({title,description,minutes,required,blocks}));setSaved("Saved");setTimeout(()=>setSaved(""),1800)}
 function add(type:BlockType){setBlocks([...blocks,{id:Date.now(),type,title:type==="Text"?"Text Section":type==="Question"?"Knowledge Check":type,content:""}])}
 function move(i:number,d:number){const n=i+d;if(n<0||n>=blocks.length)return;const c=[...blocks];[c[i],c[n]]=[c[n],c[i]];setBlocks(c)}
 return <div className="neweditor"><header className="editornav"><div className="brand"><span>ROBERTO'S</span> TRAINING</div><nav><Link href="/">Dashboard</Link><Link href="/">My Training</Link><Link href="/manager">Manager Tools</Link></nav><div className="navright">East Windsor <b className="avatar">NB</b> Nathan⌄</div></header>
 <main className="editorpage"><Link className="backlink" href="/manager/courses/new">‹ Back to Course</Link>
 <div className="editorhero"><div><div className="eyebrow">LESSON EDITOR</div><h1>{title}</h1><p>Build this lesson by adding content blocks below. Changes are saved when you choose Save Draft or Save Lesson.</p></div><div className="heroactions"><button className="previewbtn">◉ Preview Lesson</button><button className="outline" onClick={save}>Save Draft</button><button onClick={save}>Save Lesson</button></div></div>
 <div className="polishedgrid"><section>
 <div className="panel details"><h2>Lesson Details</h2><div className="detailsgrid"><label>Lesson Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Lesson Order<select><option>1. Introduction</option></select></label><label>Description <span>(shown to employees)</span><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="sidefields"><label>Estimated Time<div className="timeinput">◷ <input value={minutes} onChange={e=>setMinutes(e.target.value)}/> minutes</div></label><label className="toggleline">Required Lesson <button className={"toggle "+(required?"on":"")} onClick={()=>setRequired(!required)}><i/></button></label></div></div></div>
 <div className="panel addblock"><h2>Add Content Block</h2><div className="blocktiles">{(Object.keys(meta) as BlockType[]).map(t=><button key={t} onClick={()=>add(t)}><b>{meta[t].icon}</b><span>{t}</span></button>)}</div></div>
 <div className="panel lessoncontent"><h2>Lesson Content</h2>{blocks.map((b,i)=><div className="compactblock" key={b.id}><span className="drag">⠿</span><span className={"typeicon t"+b.type.replace(/\W/g,"")}>{meta[b.type].icon}</span><div className="blockcopy"><input value={b.title} onChange={e=>setBlocks(blocks.map(x=>x.id===b.id?{...x,title:e.target.value}:x))}/><small>{b.type}</small><textarea rows={1} value={b.content} onChange={e=>setBlocks(blocks.map(x=>x.id===b.id?{...x,content:e.target.value}:x))}/></div><div className="compactactions"><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button>✎</button><button>▣</button><button className="trash" onClick={()=>setBlocks(blocks.filter(x=>x.id!==b.id))}>♲</button><button>⌄</button></div></div>)}</div>
 </section>
 <aside className="panel employeepreview"><div className="previewhead"><div><div className="eyebrow">EMPLOYEE PREVIEW</div><p>This is how the lesson will appear to employees.</p></div><div className="devices"><button>▣</button><button>▭</button><button>▯</button></div></div><div className="previewbanner"><div><h2>{title}</h2><span>◷ {minutes} minutes　▤ 1 of 1 lessons</span></div><button>Start Lesson</button></div>
 {blocks.map(b=><div className="employeecontent" key={b.id}><span className={"typeicon t"+b.type.replace(/\W/g,"")}>{meta[b.type].icon}</span><div><h3>{b.title}</h3>{b.type==="Checklist"?<div className="checkpreview">{b.content.split("\n").filter(Boolean).map(x=><label key={x}><input type="checkbox"/>{x}</label>)}</div>:b.type==="Video"?<div className="videopreview"><div className="videologo">ROBERTO'S<small>AMERICAN TAVERN</small></div><b>▶</b><div className="videobar"/></div>:<p>{b.content}</p>}</div></div>)}
 </aside></div>{saved&&<div className="toast">✓ {saved}</div>}</main></div>