"use client";
import Link from "next/link";import {useMemo,useState} from "react";import EmployeeNav from "../../components/EmployeeNav";
const bank=[
{q:"What sauce is served with the Mediterranean Bowl?",a:["Chipotle ranch","Creamy yogurt dill","Dill tartar","Bang bang sauce"],c:1},
{q:"Which pizza has marinara, creamy vodka sauce and a pesto swirl?",a:["White Pie","Roberto Grande","The MVP","Veggie Supreme"],c:2},
{q:"What comes with the Bourbon Marinated Steak Tips?",a:["Mashed potatoes and broccolini","Truffle parmesan fries and house slaw","Parmesan risotto","Seasonal vegetables"],c:1},
{q:"Which wing option is a dry rub?",a:["General Tso","Garlic parm","Maple bourbon","Buffalo"],c:2},
{q:"What protein choices are offered for Nicola's Classic Parm?",a:["Chicken or eggplant","Chicken or veal","Eggplant or shrimp","Chicken only"],c:0},
{q:"What dressing is used on the Santa Fe Salad?",a:["Caesar","Blue cheese","Chipotle ranch","Yogurt dill"],c:2},
{q:"What accompanies the Fish & Chips?",a:["Fries, house slaw and dill tartar","Onion rings and ranch","Mashed potatoes and vegetables","Truffle fries and slaw"],c:0},
{q:"What makes the Tuscan Pepperoni pizza sweet and spicy?",a:["Mango habanero","Hot honey drizzle","Chipotle aioli","Pesto"],c:1},
{q:"What is on the Double Smash Burger?",a:["Bacon and fried egg","Two patties, grilled onions, cheddar, pickles and secret sauce","Guacamole and pickled onions","BBQ sauce and bacon"],c:1},
{q:"Which ingredients are on the Pan Seared Salmon plate?",a:["Parmesan risotto, roasted corn, black beans and charred cherry tomatoes","Mashed potatoes and broccolini","Mushroom risotto and lemon beurre blanc","Fries and house slaw"],c:0},
{q:"What is served with the Quesadilla?",a:["Ranch and guacamole","Pico de gallo and sour cream","Slaw and avocado sauce","Marinara"],c:1},
{q:"What should you do if a guest tells you they have a food allergy?",a:["Guess based on the menu icons","Tell them every dish is safe","Follow the restaurant's allergy procedure and do not guess","Recommend only salads"],c:2}
];
export default function MenuQuiz(){const questions=useMemo(()=>[...bank].sort(()=>Math.random()-.5).slice(0,10),[]),[i,setI]=useState(0),[pick,setPick]=useState<number|null>(null),[score,setScore]=useState(0),[done,setDone]=useState(false);const q=questions[i];function choose(n:number){if(pick!==null)return;setPick(n);if(n===q.c)setScore(s=>s+1)}function next(){if(i===questions.length-1){setDone(true);return}setI(i+1);setPick(null)}return <><EmployeeNav/><main className="wrap practicequiz"><Link className="backlink" href="/study">‹ Study Materials</Link>{done?<section className="card practiceresult"><div className="eyebrow">PRACTICE COMPLETE</div><h1>{score} / {questions.length}</h1><h2>{score>=8?"Nice work!":"Keep practicing"}</h2><p>This was practice only and does not affect your official training record.</p><div className="formactions"><Link className="outline editlink" href="/courses/server/menu-flashcards">Review Flashcards</Link><button onClick={()=>location.reload()}>Practice Again</button></div></section>:<><div className="quiztop"><div><div className="eyebrow">MENU KNOWLEDGE • PRACTICE QUIZ</div><h1>Quick Menu Quiz</h1><p className="muted">10 randomized questions • Ungraded practice</p></div><b>{i+1} / {questions.length}</b></div><div className="practicebar"><i style={{width:((i+1)/questions.length*100)+"%"}}/></div><section className="card practicequestion"><span className="sectionlabel">QUESTION {i+1}</span><h2>{q.q}</h2><div className="practiceanswers">{q.a.map((a,n)=><button key={a} onClick={()=>choose(n)} className={pick===null?"":n===q.c?"answercorrect":n===pick?"answerwrong":"answerdim"}>{String.fromCharCode(65+n)}. {a}</button>)}</div>{pick!==null&&<div className={pick===q.c?"practicefeedback correctfeedback":"practicefeedback wrongfeedback"}><b>{pick===q.c?"Correct":"Not quite"}</b><span>{pick===q.c?"Nice job.":"Correct answer: "+q.a[q.c]}</span></div>}<div className="practicenext"><span>Score so far: {score}</span><button disabled={pick===null} onClick={next}>{i===questions.length-1?"See Results":"Next Question →"}</button></div></section></>}</main></>}