"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";
type Req={id:number;station:string;item:string;min:number;max:number};type Entry={temp:string;note:string};
const defaults:Req[]=[
{id:1,station:"Grill",item:"Item 1",min:135,max:165},{id:2,station:"Grill",item:"Item 2",min:135,max:165},
{id:3,station:"Fry",item:"Item 1",min:135,max:165},{id:4,station:"Cold Line",item:"Item 1",min:33,max:41},
{id:5,station:"Cold Line",item:"Item 2",min:33,max:41},{id:6,station:"Prep",item:"Item 1",min:33,max:41}];
export default function LineCheck(){const [reqs,setReqs]=useState<Req[]>(defaults),[entries,setEntries]=useState<Record<number,Entry>>({}),[manager,setManager]=useState("Nathan"),[notes,setNotes]=useState(""),[done,setDone]=useState(false);
useEffect(()=>{try{const r=localStorage.getItem("robertos-line-check-requirements");if(r)setReqs(JSON.parse(r))}catch{}},[]);
const stations=useMemo(()=>[...new Set(reqs.map(x=>x.station))],[reqs]),complete=reqs.length>0&&reqs.every(r=>entries[r.id]?.temp!==""&&entries[r.id]?.temp!=null);
const danger=reqs.filter(r=>{const n=Number(entries[r.id]?.temp);return entries[r.id]?.temp!==undefined&&(n<r.min||n>r.max)});
function setEntry(id:number,key:keyof Entry,value:string){setEntries(e=>({...e,[id]:{temp:e[id]?.temp||"",note:e[id]?.note||"",[key]:value}}))}
function submit(){if(!complete)return;const report={id:Date.now(),date:new Date().toISOString(),manager,entries:reqs.map(r=>({...r,...entries[r.id],status:(Number(entries[r.id].temp)>=r.min&&Number(entries[r.id].temp)<=r.max)?"PASS":"OUT OF RANGE"})),notes,alert:danger.length>0};const old=JSON.parse(localStorage.getItem("robertos-line-check-reports")||"[]");localStorage.setItem("robertos-line-check-reports",JSON.stringify([report,...old]));setDone(true)}
if(done)return <div className="learner"><ManagerNav/><main className="wrap narrow"><section className={"linecomplete "+(danger.length?"linealert":"")}><div className="linecompleteicon">{danger.length?"!":"✓"}</div><h1>{danger.length?"Line Check Submitted — Action Required":"Line Check Complete"}</h1><p>{danger.length?danger.length+" item(s) were outside their configured temperature range. The report has been flagged for manager review.":"All required temperatures were entered and within their configured ranges."}</p><div className="actions"><button onClick={()=>window.print()} className="outline">Print Report</button><Link className="btn linkbtn" href="/manager">Manager Home</Link></div></section></main></div>;
return <div className="learner"><ManagerNav/><main className="wrap linewrap"><div className="linehero"><div><div className="eyebrow">FOOD SAFETY • MANAGER LOG</div><h1>Line Check</h1><p>Every required item must be temperature checked before this log can be submitted.</p></div><div className="lineheroactions"><Link className="outline editlink" href="/manager/line-check/history">▤ Line Check History</Link><Link className="outline editlink" href="/manager/line-check/setup">⚙ Configure Requirements</Link></div></div><section className="lineinfo card"><label>Manager<input value={manager} onChange={e=>setManager(e.target.value)}/></label><div><b>Date</b><span>{new Date().toLocaleDateString()}</span></div><div><b>Time Started</b><span>{new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</span></div><div><b>Progress</b><span>{reqs.filter(r=>entries[r.id]?.temp).length} / {reqs.length} temped</span></div></section>{stations.map(st=><section className="linestation" key={st}><div className="stationhead"><h2>{st}</h2><span>{reqs.filter(r=>r.station===st).length} required items</span></div>{reqs.filter(r=>r.station===st).map(r=>{const val=entries[r.id]?.temp,number=Number(val),bad=val!==undefined&&val!==""&&(number<r.min||number>r.max);return <div className={"lineitem "+(bad?"badtemp":"")} key={r.id}><div className="lineitemname"><strong>{r.item}</strong><small>Acceptable: {r.min}°F – {r.max}°F</small></div><label className="tempfield">Temperature <div><input inputMode="decimal" type="number" value={val||""} onChange={e=>setEntry(r.id,"temp",e.target.value)} placeholder="—"/><b>°F</b></div></label><label className="linenote">Note (optional)<input value={entries[r.id]?.note||""} onChange={e=>setEntry(r.id,"note",e.target.value)} placeholder="Corrective action, condition, etc."/></label><span className={"tempstatus "+(bad?"bad":"")}>{val?bad?"OUT OF RANGE":"PASS":"REQUIRED"}</span></div>})}</section>)}<section className="card overallnotes"><label>Overall Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add any shift notes or corrective actions..."/></label></section>{danger.length>0&&<div className="dangerbanner"><b>⚠ {danger.length} temperature{danger.length>1?"s are":" is"} outside the configured range.</b><span>Review the affected items and document corrective action before submitting.</span></div>}<div className="linesubmit"><span>{complete?"All required temperatures entered.":"Enter all "+reqs.length+" required temperatures to submit."}</span><button disabled={!complete} onClick={submit}>Complete & Sign Line Check</button></div><p className="linecaveat">Reports currently save on this browser. Automatic email and manager notifications will activate when shared backend/email delivery is connected.</p></main></div>}
function ManagerNav(){return <header className="studyvisualnav"><Link className="scriptbrand" href="/manager">Roberto's<small>TRAINING</small></Link><nav><Link href="/manager">⌂ Home</Link><Link href="/courses/server">◇ My Training</Link><Link href="/manager/study">▰ Study Materials</Link><Link href="/manager/resources">▤ Resources</Link><Link href="/progress">▥ Progress</Link></nav><div className="navavatar">NB⌄</div></header>}
