"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Q={id:number;text:string;answers:string[];correct:number};
const starter:Q[]=[{id:1,text:"When should you perform your first check-back after food is delivered?",answers:["Immediately","Within about 2 minutes / 2 bites","After 10 minutes","Only if called over"],correct:1}];
export default function QuizBuilder(){
 const [title,setTitle]=useState("Final Server Exam"),[passing,setPassing]=useState(80),[questions,setQuestions]=useState<Q[]>(starter),[saved,setSaved]=useState("");
 useEffect(()=>{try{const raw=localStorage.getItem("robertos-quiz-draft");if(raw){const d=JSON.parse(raw);setTitle(d.title||"Final Server Exam");setPassing(d.passing||80);setQuestions(d.questions?.length?d.questions:starter)}}catch{}},[]);
 function save(label="Quiz draft saved"){localStorage.setItem("robertos-quiz-draft",JSON.stringify({title,passing,questions}));setSaved(label);setTimeout(()=>setSaved(""),2200)}
 function add(){setQuestions([...questions,{id:Date.now(),text:"New question",answers:["Answer A","Answer B","Answer C","Answer D"],correct:0}])}
 function patch(id:number,data:Partial<Q>){setQuestions(questions.map(q=>q.id===id?{...q,...data}:q))}
 function answer(id:number,index:number,value:string){setQuestions(questions.map(q=>q.id===id?{...q,answers:q.answers.map((a,i)=>i===index?value:a)}:q))}
 return <div className="neweditor"><header className="editornav"><div className="brand"><span>ROBERTO'S</span> TRAINING</div><nav><Link href="/manager">Dashboard</Link><Link href="/">My Training</Link><Link href="/manager">Manager Tools</Link></nav><div className="navright">East Windsor <b className="avatar">NB</b> Nathan</div></header><main className="editorpage quizbuilder"><Link className="backlink" href="/manager/courses/new">‹ Back to Course</Link><div className="editorhero"><div><div className="eyebrow">QUIZ BUILDER</div><h1>{title}</h1><p>Create questions, answers, scoring, and passing requirements.</p></div><div className="heroactions">{saved&&<span className="saved">✓ {saved}</span>}<button className="previewbtn" onClick={()=>save("Preview saved")}>Preview</button><button className="outline" onClick={()=>save()}>Save Draft</button><button onClick={()=>save("Quiz saved")}>Save Quiz</button></div></div>
 <div className="quizlayout"><div><section className="panel quizsettings"><h2>Quiz Settings</h2><div className="formgrid"><label>Quiz Name<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Passing Score<div className="scoreinput"><input type="number" min="1" max="100" value={passing} onChange={e=>setPassing(Number(e.target.value))}/><b>%</b></div></label></div><div className="quizrules"><span>✓ Failed attempts are locked</span><span>✓ Manager controls retests</span><span>✓ All attempts and answers are recorded</span></div></section>
 <section className="panel"><div className="section-title"><div><h2>Questions</h2><p className="muted">{questions.length} question{questions.length===1?"":"s"} • {passing}% required to pass</p></div><button onClick={add}>+ Add Question</button></div>{questions.map((q,qi)=><div className="quizquestionbuilder" key={q.id}><div className="questionbuilderhead"><span>QUESTION {qi+1}</span><div><button className="outline mini" disabled={qi===0} onClick={()=>{const x=[...questions];[x[qi-1],x[qi]]=[x[qi],x[qi-1]];setQuestions(x)}}>↑</button><button className="outline mini" disabled={qi===questions.length-1} onClick={()=>{const x=[...questions];[x[qi+1],x[qi]]=[x[qi],x[qi+1]];setQuestions(x)}}>↓</button><button className="danger mini" onClick={()=>setQuestions(questions.filter(x=>x.id!==q.id))}>Delete</button></div></div><input className="questiontext" value={q.text} onChange={e=>patch(q.id,{text:e.target.value})}/><div className="answerbuilder">{q.answers.map((a,ai)=><label className={q.correct===ai?"correctchoice":""} key={ai}><input type="radio" name={"correct-"+q.id} checked={q.correct===ai} onChange={()=>patch(q.id,{correct:ai})}/><span>{String.fromCharCode(65+ai)}</span><input value={a} onChange={e=>answer(q.id,ai,e.target.value)}/><small>{q.correct===ai?"Correct Answer":"Mark Correct"}</small></label>)}</div></div>)}</section></div>
 <aside className="panel quizsummary"><div className="eyebrow">QUIZ SUMMARY</div><h2>{title}</h2><div className="summaryscore"><strong>{passing}%</strong><span>Passing Score</span></div><div className="summaryline"><span>Questions</span><b>{questions.length}</b></div><div className="summaryline"><span>Retake Policy</span><b>Manager Released</b></div><div className="summaryline"><span>Attempts</span><b>Tracked</b></div><hr/><p className="muted">Select the radio button beside an answer to mark it as the correct response.</p></aside></div></main></div>
}