"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
const base="https://xtuhannfnvsvvahrzyxj.supabase.co";
const apiKey="sb_publishable_IygQd5vrXido1h8FMRjuaA_QrNzgFEC";
type Person={user_id:string;email:string;display_name:string;access_role:string;staff_position:string|null};
const positions=[["","Not assigned"],["server","Server"],["bartender","Bartender"],["kitchen","Kitchen"],["hot","Hot"],["host","Host (Support Staff)"],["busser","Busser (Support Staff)"]];
export default function Employees(){
 const [people,setPeople]=useState<Person[]>([]),[token,setToken]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState("");
 async function load(t:string){const response=await fetch(base+"/rest/v1/staff_profiles?select=user_id,email,display_name,access_role,staff_position&order=display_name.asc",{headers:{apikey:apiKey,Authorization:"Bearer "+t}});if(!response.ok)throw Error("Unable to load employees ("+response.status+").");setPeople(await response.json())}
 useEffect(()=>{async function start(){try{const saved=sessionStorage.getItem("robertos_auth");if(!saved)throw Error("Please sign in first.");const t=JSON.parse(saved).access_token;const me=await fetch(base+"/auth/v1/user",{headers:{apikey:apiKey,Authorization:"Bearer "+t}});if(!me.ok)throw Error("Session expired. Please sign in again.");const user=await me.json();const p=await fetch(base+"/rest/v1/staff_profiles?user_id=eq."+user.id+"&select=access_role",{headers:{apikey:apiKey,Authorization:"Bearer "+t}});if(!p.ok)throw Error("Could not verify permissions.");const roles=await p.json();if(roles[0]?.access_role!=="admin")throw Error("Only administrators can manage employee roles.");setToken(t);await load(t)}catch(e){setError(e instanceof Error?e.message:"Unable to load")}finally{setLoading(false)}}start()},[]);
 async function update(person:Person,field:"access_role"|"staff_position"|"display_name",value:string){setSaving(person.user_id);setError("");try{const response=await fetch(base+"/rest/v1/staff_profiles?user_id=eq."+person.user_id,{method:"PATCH",headers:{apikey:apiKey,Authorization:"Bearer "+token,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({[field]:field==="staff_position"?(value||null):value})});if(!response.ok)throw Error("Could not save employee changes.");const updated=await response.json();if(updated.length!==1)throw Error("Employee was not updated.");setPeople(old=>old.map(p=>p.user_id===person.user_id?updated[0]:p))}catch(e){setError(e instanceof Error?e.message:"Save failed")}finally{setSaving("")}}
 return <main className="wrap" style={{paddingTop:36}}><Link href="/manager">← Manager Dashboard</Link><h1>Employee Management</h1><p>Assign account access and staff positions. New employees can register from the sign-in page and will appear here after registration.</p>{error&&<div className="card" role="alert" style={{padding:18,marginBottom:20,color:"#b71922"}}>{error} <Link href="/login">Sign in</Link></div>}{loading?<p>Loading employees…</p>:<section className="card" style={{padding:24,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",textAlign:"left"}}><thead><tr><th>Name / Email</th><th>Access</th><th>Position</th><th>Status</th></tr></thead><tbody>{people.map(person=><tr key={person.user_id} style={{borderTop:"1px solid #dce3e9"}}><td style={{padding:"15px 8px"}}><input aria-label={"Name for "+person.email} defaultValue={person.display_name} key={person.user_id+person.display_name} onBlur={e=>{if(e.target.value!==person.display_name)update(person,"display_name",e.target.value)}} style={{padding:8,maxWidth:190,display:"block"}}/><small>{person.email}</small></td><td><select aria-label={"Role for "+person.email} value={person.access_role} disabled={!token||saving===person.user_id||person.email.toLowerCase()==="natebarry11@gmail.com"} onChange={e=>update(person,"access_role",e.target.value)} style={{padding:8}}><option value="staff">Staff</option><option value="manager">Manager</option><option value="admin">Admin</option></select></td><td><select aria-label={"Position for "+person.email} value={person.staff_position||""} disabled={!token||saving===person.user_id} onChange={e=>update(person,"staff_position",e.target.value)} style={{padding:8}}>{positions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></td><td>{saving===person.user_id?"Saving…":"Saved"}</td></tr>)}</tbody></table>{!people.length&&!error&&<p>No employees registered yet.</p>}</section>}<p style={{marginTop:20}}><Link href="/login">Employee registration →</Link></p></main>
}